### ISSUE TITLE
TODO: complete uTLS examples

### ISSUE THREAD

**Issue by gaukas** [gaukas/watm#9]
Before we can call `utls.wasm` complete, the following must be done:

- [x] uTLS.wasm compiles and runs
- [x] uTLS is configurable with JSON config file
- [ ] Optional: able to pull connection states from uTLS (v1 needed?)

**Comment by erikziyunchi** [comment]
Also maybe good to have the same behavior with loading at the Rust-side runtime.

**Comment by gaukas** [comment]
I think it should given the WATM itself isn't designed per target runtime but per target spec/API version, but it is good to keep in mind. I think we still need to nitpick and fix all the discrepancies between the two runtime libraries we have for now.
